package com.faradhy.citarasabunda.model

import com.faradhy.citarasabunda.R

object FoodFakeDataSource {
    val dummyFoodFoodMenus = listOf(
        FoodMenu(1, R.drawable.sop_konro, "Sop Konro", 30000, "Sop Konro adalah hidangan tradisional dari daerah Makassar, Sulawesi Selatan, Indonesia. Hidangan ini terkenal karena menggunakan bahan dasar iga sapi yang dimasak dengan bumbu rempah khas, sehingga menghasilkan sup yang kaya akan rasa"),
        FoodMenu(2, R.drawable.rawon, "Rawon", 24000, "Rawon adalah hidangan khas Indonesia yang berasal dari Jawa Timur. Hidangan ini terkenal karena kuahnya yang berwarna hitam pekat, disebabkan oleh penggunaan bumbu keluak (buah keluak) yang memberikan cita rasa khas dan aroma unik"),
        FoodMenu(3, R.drawable.soto_padang, "Soto Padang", 25000, "Soto Padang adalah varian soto yang berasal dari daerah Padang, Sumatra Barat, Indonesia. Hidangan ini memiliki ciri khas tersendiri dan membedakannya dari soto-soto dari daerah lain di Indonesia. Salah satu perbedaannya terletak pada bumbu kuah yang kaya dan rasa gurih yang khas"),
        FoodMenu(4, R.drawable.bubur_manado, "Bubur Manado", 25000, "Bubur Manado adalah hidangan tradisional dari daerah Manado, Sulawesi Utara, Indonesia. Hidangan ini adalah bentuk bubur atau bubur ketan yang khas dari budaya Manado. Berikut adalah beberapa ciri khas Bubur Manado"),
        FoodMenu(5, R.drawable.sate_lilit_bali, "Sate Lilit Bali", 25000, "Sate Lilit Bali adalah hidangan sate yang berasal dari pulau Bali, Indonesia. Ciri khas Sate Lilit terletak pada cara pembuatannya yang unik, yaitu daging yang dibungkus secara melingkar pada bambu atau batang serai sebelum dipanggang"),
        FoodMenu(6, R.drawable.candil_ketan, "Candil Ketan", 17000, "Candil ketan adalah hidangan kue tradisional Indonesia yang umumnya terbuat dari ketan yang dibentuk bulat kecil dan diberi lapisan kelapa parut. Hidangan ini sering disajikan dalam kuah gula kelapa atau kuah santan, memberikan cita rasa manis yang lezat"),
        FoodMenu(7, R.drawable.pempek_palembang, "Pempek Palembang", 40000, "Pempek Palembang adalah hidangan khas dari Palembang, Sumatra Selatan, Indonesia. Hidangan ini terkenal karena terbuat dari adonan ikan yang dicampur dengan tepung sagu atau kanji, kemudian dibentuk dan direbus atau digoreng. Pempek umumnya disajikan dengan saus cuko, yang merupakan campuran cuka, gula merah, garam, bawang putih, dan cabai"),
        FoodMenu(8, R.drawable.seblak_bandung, "Seblak Bandung", 20000, "Seblak Bandung adalah hidangan khas dari Bandung, Jawa Barat, Indonesia. Hidangan ini merupakan salah satu kuliner yang cukup populer di Indonesia, terutama di daerah Jawa Barat. Seblak Bandung memiliki rasa yang khas dan berbeda dari makanan lainnya karena bumbu dan cara penyajiannya"),
        FoodMenu(9, R.drawable.batagor_bandung, "Batagor Bandung", 20000, "Batagor adalah singkatan dari \"Bakso Tahu Goreng\" yang merupakan hidangan khas dari Bandung, Jawa Barat, Indonesia. Batagor terkenal sebagai salah satu jenis makanan jalanan yang populer dan memiliki cita rasa yang khas. Hidangan ini biasanya terdiri dari bakso (bulat daging yang biasanya terbuat dari campuran ikan tenggiri dan tepung tapioka)"),
        FoodMenu(10, R.drawable.tahu_tek, "Tahu Tek", 25000, "Tahu Tek adalah hidangan khas yang berasal dari Surabaya, Jawa Timur, Indonesia. Hidangan ini terdiri dari tahu goreng yang disajikan dengan kuah kacang kental dan berbagai bumbu serta tambahan lainnya. \"Tek\" dalam nama hidangan ini konon berasal dari kata \"potek,\" yang berarti kurang atau tidak ada"),
        FoodMenu(11, R.drawable.tahu_campur, "Tahu Campur", 35000, "Tahu Campur adalah hidangan khas dari Surabaya, Jawa Timur, Indonesia. Hidangan ini terdiri dari berbagai komponen, termasuk tahu goreng, lontong atau ketupat, soun (sohun atau bihun), tauge, dan disajikan dengan kuah kacang kental. Hidangan ini kemudian diberi bumbu kacang, kecap manis, bawang goreng, dan kadang-kadang tambahan sambal untuk rasa pedas"),
        FoodMenu(12, R.drawable.rujak_cingur, "Rujak Cingur", 35000, "Rujak Cingur adalah hidangan khas dari Surabaya, Jawa Timur, Indonesia. Hidangan ini merupakan variasi dari rujak, tetapi memiliki tambahan bahan cingur, yang merupakan potongan daging dari hidung sapi yang direbus hingga empuk. Nama \"cingur\" sendiri berasal dari bahasa Jawa yang berarti \"hidung"),
    )
}